name: notium
description: Let your ideas flow. A note editor built for focus, simplicity and privacy.
version: 1.0.1+11

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.0.1
  badges: ^1.1.1
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.6+1
  dart_git:
    git:
      url: https://github.com/notium/dart_git.git
      ref: 071cb643a4924a45986920f44c0e2433ee9159ed
  device_info: ">=0.4.2+4 <2.0.0"
  dots_indicator: ^0.0.3
  dynamic_theme: ^1.0.0
  easy_localization: ^2.3.2
  easy_localization_loader: ^0.0.2
  equatable: ^1.1.0
  fimber: ^0.3.0
  flutter_email_sender: ^3.0.1
  flutter_emoji: ">= 2.0.0"
  flutter_markdown: ^0.4.3
  flutter_plugin_android_lifecycle: ^1.0.8 # for fixing the build
  flutter_sentry: ^0.4.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.7.0
  function_types: ^0.0.2
  git_bindings: #^0.0.18
    git:
      url: https://github.com/notium/git_bindings.git
      ref: 2598c4cf21c4e23639b7eb5f3e1dd66cfd8eccd9
  git_url_parse2: ^0.0.1
  http: ^0.12.0+1
  image_picker: ^0.6.7
  intl: ^0.16.1
  isolate: ^2.0.3
  mutex: ^1.0.3
  package_info: ">=0.4.1 <2.0.0"
  path: ^1.6.2
  provider: ^4.3.2+2
  receive_sharing_intent: ^1.4.0+2
  sentry: ">=3.0.0 <4.0.0"
  share: ^0.6.3+5
  shared_preferences: ^0.5.6
  ssh_key: ^0.5.1
  steel_crypt: ^1.7.1+1
  synchronized: ^2.2.0
  timeago: ^2.0.27
  url_launcher: ^5.4.1
  uuid: ^2.0.1
  yaml: ^2.2.0
  yaml_serializer: ^0.0.8

dev_dependencies:
  benchmark_harness: any
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter
  import_sorter: ^4.2.2
  screenshots: ^2.1.1
  test: ^1.5.1

dependency_overrides:
  file: ^6.0.0-nullsafety.1
  markdown:
    git: https://github.com/notium/markdown.git
    # Required for screenshots package
  process: ^4.0.0-nullsafety.1
  platform: ^3.0.0-nullsafety.1

flutter:
  uses-material-design: true
  assets:
    # Images
    - "assets/git-hosting.png"
    - "assets/icon/icon.png"
    - "assets/icon/icon_black.png"
    - "assets/icon/done-icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/icon/help-icon.png"
    - "assets/less.png"
    # Language files
    - "assets/langs/en.yaml"
    - "assets/langs/fr.yaml"
  fonts:
    # For debug and changes count
    - family: IBMPlexMono-Light
      fonts:
        - asset: fonts/IBMPlexMono-Light.ttf
        - asset: fonts/IBMPlexMono-LightItalic.ttf
    # Main font
    - family: IBMPlexSans-Extralight
      fonts:
        - asset: fonts/IBMPlexSans-ExtraLight.ttf
        - asset: fonts/IBMPlexSans-ExtraLightItalic.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
