version: 2
jobs:
  build:
    docker:
      - image: vhanda/flutter-android:latest
    steps:
      - checkout
      - run:
          name: Setup Flutter Env
          command: /opt/flutter/bin/cache/dart-sdk/bin/dart ./scripts/setup_env.dart
      - run:
          name: SSH Problem
          command: echo 'Host *\n    StrictHostKeyChecking no' > ~/.ssh/config
      - run:
          name: Current Directory
          command: pwd
      - run:
          name: List Directory
          command: ls -l
      - run:
          name: Test
          command: flutter test -j 1 --coverage --machine | tojunit --output junit.xml
      - store_test_results:
          path: ./
      - run:
          name: Analyze
          command: flutter analyze
      - run:
          name: Decode Android key store
          command: echo "$KEYSTORE" | base64 -di > android/app/keystore.jks
      - run:
          name: Create Google Play key
          command: echo "$GOOGLE_PLAY_KEY" | base64 -di > android/google-play-api-key.json
      - run:
          name: Create Android Key file
          command: echo "$ANDROID_KEY_FILE" | base64 -di > android/key.properties
      - run:
          name: Build
          command: ./scripts/build.sh
      - store_artifacts:
          path: build/app/outputs/bundle/prodRelease/app.aab
          destination: notium.aab
      - run:
          name: Generate Test Coverage
          command: ./scripts/test_coverage.sh
      - store_artifacts:
          path: coverage
#      - run:
#          name: Upload Crashlytics Symbols
#          command: ./scripts/android_crashlytics.sh
      - run:
          name: Publish Alpha
          command: cd android && fastlane alphaBuild
