name: Trigger Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to simplewave.net
        run: 'curl -X POST ''https://api.github.com/repos/simplewave/simplewave.net/actions/workflows/main.yml/dispatches'' -u "vHanda:${{secrets.ACCESS_TOKEN_GITHUB}}" -H "Content-Type: application/json" --data ''{"ref": "master"}'''
        env:
          ACCESS_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_GITHUB }}
